const state={mode:null,subject:null,lesson:null,language:"ar"};
const $=id=>document.getElementById(id);
const show=id=>{["welcome","subjects","lesson"].forEach(name=>$(name).classList.toggle("hidden",name!==id));$(id).focus?.()};
function speak(text){if(!("speechSynthesis" in window))return; speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=state.language==="ar"?"ar-SA":"en-US";utterance.rate=.88;speechSynthesis.speak(utterance)}
function voiceStatus(text,on=true){$("voice-status").textContent=text;$("voice-status").classList.toggle("active",on);if(on)setTimeout(()=>voiceStatus("",false),3500)}
function listen(callback){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){voiceStatus("التعرف على الصوت غير مدعوم هنا. يمكنك الكتابة بدلًا منه.");return}const recognition=new Recognition();recognition.lang=state.language==="ar"?"ar-EG":"en-US";recognition.interimResults=false;recognition.onstart=()=>voiceStatus("أستمع إليك الآن…");recognition.onerror=()=>voiceStatus("لم أسمع بوضوح. حاول مرة أخرى.");recognition.onresult=e=>callback(e.results[0][0].transcript);recognition.start()}
document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{state.mode=button.dataset.mode;document.body.className=`mode-${state.mode}`;show("subjects");speak("اختر الرياضيات أو مهارات الحاسب")}));
async function chooseSubject(subject){if(subject!=="math"){voiceStatus("محتوى مهارات الحاسب سيضاف قريبًا");speak("محتوى مهارات الحاسب سيضاف قريبًا");return}state.subject=subject;const response=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,query:"خواص الضرب",language:state.language})});if(!response.ok){voiceStatus("تعذر تحميل الدرس");return}state.lesson=await response.json();$("lesson-title").textContent=state.lesson.title;$("lesson-text").textContent=state.lesson.explanation;$("lesson-source").textContent="من المنهج المعتمد";$("question").textContent=state.lesson.question;show("lesson");speak(`${state.lesson.title}. ${state.lesson.explanation}`)}
document.querySelectorAll("[data-subject]").forEach(button=>button.addEventListener("click",()=>chooseSubject(button.dataset.subject)));
$("listen-subject").addEventListener("click",()=>listen(text=>chooseSubject(/رياض|math/i.test(text)?"math":"ict")));
$("speak-lesson").addEventListener("click",()=>speak(state.lesson?.explanation||""));
$("start-question").addEventListener("click",()=>{$("question-box").classList.remove("hidden");speak(state.lesson.question);$("answer").focus()});
$("listen-answer").addEventListener("click",()=>listen(text=>{$("answer").value=text;voiceStatus(`سمعت: ${text}`)}));
$("submit-answer").addEventListener("click",async()=>{const value=$("answer").value.trim();if(!value){voiceStatus("من فضلك قل أو اكتب إجابتك");return}const response=await fetch("/api/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson_id:state.lesson.lesson_id,answer:value})});const result=await response.json();const feedback=state.language==="ar"?result.feedback_ar:result.feedback_en;$("feedback").textContent=feedback;speak(feedback)});
$("language").addEventListener("click",()=>{state.language=state.language==="ar"?"en":"ar";document.documentElement.lang=state.language;document.documentElement.dir=state.language==="ar"?"rtl":"ltr";$("language").textContent=state.language==="ar"?"English":"العربية";voiceStatus(state.language==="ar"?"تم اختيار العربية":"English selected")});

