const state={mode:null,subject:null,lesson:null,language:"ar",questionIndex:0,lessonStep:0,group:{socket:null,role:null,name:null,code:null,hostToken:null,current:null}};
const $=id=>document.getElementById(id);
const panels=["welcome","subjects","lesson","group"];
const show=id=>{panels.forEach(name=>$(name).classList.toggle("hidden",name!==id));$(id).setAttribute("tabindex","-1");$(id).focus()};

function speak(text,onEnd){if(!("speechSynthesis" in window)){onEnd?.();return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=state.language==="ar"?"ar-SA":"en-US";utterance.rate=.88;utterance.onend=()=>onEnd?.();speechSynthesis.speak(utterance)}
function voiceStatus(text,on=true){$("voice-status").textContent=text;$("voice-status").classList.toggle("active",on);if(on)setTimeout(()=>voiceStatus("",false),3500)}
function listen(callback){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){voiceStatus("التعرف على الصوت غير مدعوم. استخدم الأزرار أو الكتابة.");return}const recognition=new Recognition();recognition.lang=state.language==="ar"?"ar-EG":"en-US";recognition.interimResults=false;recognition.onstart=()=>voiceStatus("أستمع إليك الآن…");recognition.onerror=event=>voiceStatus(event.error==="not-allowed"?"اسمح للمتصفح باستخدام الميكروفون ثم حاول مرة أخرى.":"لم أسمع بوضوح. حاول مرة أخرى.");recognition.onresult=e=>callback(e.results[0][0].transcript);recognition.start()}
function listenForSubject(){listen(text=>{if(/رياض|حساب|math/i.test(text))chooseSubject("math");else if(/حاسب|كمبيوتر|ict/i.test(text))chooseSubject("ict");else speak("لم أفهم الاختيار. قل رياضيات أو أساسيات كمبيوتر.",listenForSubject)})}
function promptForSubject(){speak("هل تريد الرياضيات أم أساسيات الكمبيوتر؟ قل اختيارك بعد سماع الرسالة.",listenForSubject)}

document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{state.mode=button.dataset.mode;document.body.className=`mode-${state.mode}`;show("subjects");if(state.mode==="vision")promptForSubject();else speak("اختر الرياضيات أو أساسيات الكمبيوتر")}));

async function chooseSubject(subject){state.subject=subject;const query=subject==="math"?"خواص الضرب":"ما هو الكمبيوتر";const response=await fetch("/api/tutor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,query,language:state.language})});if(!response.ok){voiceStatus("تعذر تحميل الدرس");return}state.lesson=await response.json();state.lessonStep=0;state.questionIndex=0;$("lesson-title").textContent=state.lesson.title;$("lesson-source").textContent=state.lesson.review_status==="approved"?"من المنهج المعتمد":"نسخة محتوى قيد مراجعة المعلم";show("lesson");playLesson()}
function playLesson(){const steps=state.lesson.lesson_steps||[state.lesson.explanation];const play=index=>{state.lessonStep=index;$("lesson-text").textContent=steps[index];speak(steps[index],()=>{if(index+1<steps.length)play(index+1);else finishLesson()})};play(0)}
function finishLesson(){const message="انتهى شرح الدرس. هل تريد التدريب بمفردك أم إنشاء جلسة جماعية؟";$("lesson-text").textContent+=`\n\n${message}`;$("start-question").classList.remove("hidden");$("create-group").classList.remove("hidden");speak(message)}
function currentQuestion(){return state.lesson.questions[state.questionIndex]}
function beginIndividual(){const question=currentQuestion();$("question-box").classList.remove("hidden");$("question").textContent=question.text;$("answer").value="";$("feedback").textContent="";speak(question.text);$("answer").focus()}

document.querySelectorAll("[data-subject]").forEach(button=>button.addEventListener("click",()=>chooseSubject(button.dataset.subject)));
$("listen-subject").addEventListener("click",listenForSubject);$("speak-lesson").addEventListener("click",playLesson);$("start-question").addEventListener("click",beginIndividual);
$("listen-answer").addEventListener("click",()=>listen(text=>{$("answer").value=text;voiceStatus(`سمعت: ${text}`)}));
$("submit-answer").addEventListener("click",async()=>{const value=$("answer").value.trim();if(!value){voiceStatus("من فضلك قل أو اكتب إجابتك");return}const question=currentQuestion();const response=await fetch("/api/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson_id:state.lesson.lesson_id,question_id:question.id,answer:value})});const result=await response.json();const feedback=state.language==="ar"?result.feedback_ar:result.feedback_en;$("feedback").textContent=feedback;speak(feedback,()=>{if(result.correct&&state.questionIndex+1<state.lesson.questions.length){state.questionIndex++;beginIndividual()}else if(result.correct)speak("أكملت أسئلة الدرس. أحسنت!")})});

function wsUrl(code,name,role,token=""){const protocol=location.protocol==="https:"?"wss":"ws";return `${protocol}://${location.host}/ws/group/${code}?name=${encodeURIComponent(name)}&role=${role}&token=${encodeURIComponent(token)}`}
function connectGroup(code,name,role,token=""){state.group={socket:new WebSocket(wsUrl(code,name,role,token)),role,name,code,hostToken:token,current:null};$("group-join-form").classList.add("hidden");$("group-room").classList.remove("hidden");$("room-code-display").textContent=code;if(role==="host")$("start-group").classList.remove("hidden");state.group.socket.onmessage=event=>handleGroupMessage(JSON.parse(event.data));state.group.socket.onerror=()=>voiceStatus("تعذر الاتصال بالغرفة");state.group.socket.onclose=()=>{$("group-status").textContent="انقطع الاتصال بالغرفة."}}
function handleGroupMessage(message){if(message.type==="room_state"){$("participants").innerHTML=message.participants.map(name=>`<li>${name}</li>`).join("");state.group.current=message.current_participant;$("group-status").textContent=message.active?`الدور الآن على ${message.current_participant}`:"في انتظار بدء المعلم";return}if(message.type==="question"){$("group-question-box").classList.toggle("hidden",state.group.role!=="participant");$("group-question").textContent=`سؤال ${message.participant}: ${message.text}`;const announcement=`الدور على ${message.participant}. ${message.text}`;speak(announcement,()=>{if(state.mode==="vision"&&state.group.name===message.participant)listen(text=>{$("group-answer").value=text})});return}if(message.type==="feedback"||message.type==="complete"||message.type==="error"){$("group-status").textContent=message.message;speak(message.message);if(message.type==="complete")$("group-question-box").classList.add("hidden")}}
$("join-group-home").addEventListener("click",()=>show("group"));
$("create-group").addEventListener("click",async()=>{const response=await fetch("/api/group/rooms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson_id:state.lesson.lesson_id})});const room=await response.json();show("group");connectGroup(room.code,"المعلم","host",room.host_token);speak(`تم إنشاء الغرفة. الرمز هو ${room.code.split("").join(" ")}`)});
$("join-group").addEventListener("click",()=>{const code=$("group-code").value.trim().toUpperCase(),name=$("participant-name").value.trim();if(!code||!name){voiceStatus("أدخل رمز الغرفة والاسم المستعار");return}connectGroup(code,name,"participant")});
$("start-group").addEventListener("click",()=>state.group.socket?.send(JSON.stringify({type:"start"})));
$("group-listen-answer").addEventListener("click",()=>listen(text=>{$("group-answer").value=text}));
$("send-group-answer").addEventListener("click",()=>{const answer=$("group-answer").value.trim();if(answer)state.group.socket?.send(JSON.stringify({type:"answer",answer}))});
$("language").addEventListener("click",()=>{state.language=state.language==="ar"?"en":"ar";document.documentElement.lang=state.language;document.documentElement.dir=state.language==="ar"?"rtl":"ltr";$("language").textContent=state.language==="ar"?"English":"العربية";voiceStatus(state.language==="ar"?"تم اختيار العربية":"English selected")});
